### PR TITLE
Creating a blob with meta data broken

### PR DESCRIPTION
**Pull request by lailabougria**
Given that the metadata is now retrieved in a separate call, the blob needs to be uploaded before the metadata can be manipulated. Setting the valid until was failing for all new blobs.

### CODE REVIEW

**Review by danielmarbach — APPROVED** [review]

**Review by SeanFeldman — APPROVED** [review]
I think the test name is somewhat misleading. Wherever there is an expiry date set or not, it should work. The expiry date is for the automated clean-up which is not verified in the test.
Saying that as we are considering to deprecate automated cleanup, this test won't matter much at that point.

**Comment by danielmarbach** [comment]
I don't think the statement is true. Expiry matters because it is the one that triggers us writing the meta data. The meta data is also used in our cleanup examples and not just the cleanup logic in the databus. We could change it to assert metadata and then make the should reflect that.

**Comment by SeanFeldman** [comment]
> We could change it to assert metadata and then make the should reflect that.

If that would happen then the name would reflect what we're verifying. ATM, the test is solely validating that the message arrives and nothing about the expiry. 

Either way, I'm not going to block this 🙂

**Comment by lailabougria** [comment]
Sounds off to me to keep that in an acceptance test then. Looks like we want to test the specifics of how creation happens when cleanup is configured, which I would move to an integration test

**Comment by SeanFeldman** [comment]
Let's pause for a second. What's this discussion is providing if we're going to deprecate the built-in cleanup? 😀

**Comment by danielmarbach** [comment]
That's besides the point because as I said even if we remove the cleanup we
need to support the scenario of having expiry turned into valid until
metadata for the cleanup scenario done by function for example to work.

Laila, let's reads an integration test by resurrecting one of your commits.
I'll be around shortly if you need assistance

Sean Feldman <notifications@github.com> schrieb am Fr., 30. Okt. 2020,
07:12:

**Pull request merged**
